// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

package constants

import (
	"net"
	"strconv"
	"time"
)

const (
	// OperatorName is the name of the scalingadvisor operator.
	OperatorName = "scalingadvisor"
	// OperatorConfigGroupName is the group name for OperatorConfiguration
	OperatorConfigGroupName = "config.sa.gardener.cloud"
	// OperatorGroupName is the name of the group for all scaling recommender custom resources.
	OperatorGroupName = "sa.gardener.cloud"
)

const (
	// KindOperatorConfig is the KIND for scaling advisor operator configuration.
	KindOperatorConfig = "OperatorConfig"
	// KindScalingAdvice is the KIND for ClusterScalingAdvice generated by the scaling-advisor operator.
	KindScalingAdvice = "ScalingAdvice"
	// KindScalingConstraint is the KIND for constraint object that is reconciled by the scaling-advisor operator in order to generate the scaling advice.
	KindScalingConstraint = "ScalingConstraint"
)

const (
	// AnnotationEnableScalingDiagnostics is the annotation key to enable scaling diagnostics for a cluster.
	// This is applied by a user/tool on the ClusterScalingConstraint object which produces diagnostics within
	// the generated ClusterScalingAdvice.Status.
	AnnotationEnableScalingDiagnostics = "sa.gardener.cloud/enable-scaling-diagnostics"
)

const (
	// LabelSimulationName is the label key to identify name of the simulation inside a simulation group.
	LabelSimulationName = "sa.gardener.cloud/simulation-name"
	// LabelSimulationGroupName is the label key to identify the name of the simulation group.
	LabelSimulationGroupName = "sa.gardener.cloud/simulation-group-name"
	// LabelSimulationGroupNumPasses is the label key to identify the number of passes made for this simulation group.
	LabelSimulationGroupNumPasses = "sa.gardener.cloud/simulation-group-num-passes"
	// LabelNodePoolName is the label key to identify the node pool name for which the simulation is being run.
	LabelNodePoolName = "sa.gardener.cloud/node-pool-name"
	// LabelNodeTemplateName is the label key to identify the node template name for which the simulation is being run.
	LabelNodeTemplateName = "sa.gardener.cloud/node-template-name"
	// LabelRequestID is the label key to identify the request Name of scaling advice request.
	LabelRequestID = "sa.gardener.cloud/request-id"
	// LabelCorrelationID is the label key to identify the correlation Name of the scaling advice request.
	LabelCorrelationID = "sa.gardener.cloud/correlation-id"
	// LabelTotalSimulationRuns is the label key to indicate the total number of simulation runs made across all simulation groups to produce ScaleOutPlan
	LabelTotalSimulationRuns = "sa.gardener.cloud/total-simulation-runs"

	// LabelPlanGenerateDuration is the label key for the duration taken for the scaling planner to generate a scaling plan for a request.
	LabelPlanGenerateDuration = "sa.gardener.cloud/plan-generate-duration"

	// LabelConstraintNumPools is the label key for the number of pools in the scaling constraint.
	LabelConstraintNumPools = "sa.gardener.cloud/constraint-num-pools"

	// LabelSnapshotNumUnscheduledPods is the label key for the number of unscheduled pods in the snapshot.
	LabelSnapshotNumUnscheduledPods = "sa.gardener.cloud/snapshot-num-unscheduled-pods"
)

const (
	// DefaultOperatorHealthProbePort is the default port for the operator health probe endpoints.
	DefaultOperatorHealthProbePort = 8081
	// DefaultOperatorMetricsPort is the default port for the operator metrics endpoint.
	DefaultOperatorMetricsPort = 8082
	// DefaultOperatorProfilingPort is the default port for the operator profiling endpoints.
	DefaultOperatorProfilingPort = 8083
	// DefaultAdvisorServicePort is the default port for the scaling advisor service.
	DefaultAdvisorServicePort = 8090
	// DefaultMinKAPIPort is the default port for the MinKAPI core.
	DefaultMinKAPIPort = 8091

	// DefaultGracefulShutdownTimeout is the default timeout for graceful shutdown of a server
	DefaultGracefulShutdownTimeout = 10 * time.Second
)

var (
	// DefaultOperatorHealthProbeBindAddress is the default bind address serving the /healthz (liveness) and /readyz (readiness) endpoints for the scaling-advisor operator
	DefaultOperatorHealthProbeBindAddress = net.JoinHostPort("", strconv.Itoa(DefaultOperatorHealthProbePort))

	// DefaultOperatorMetricsBindAddress is the default bind address serving the /metrics endpoint for the scaling-advisor operator.
	DefaultOperatorMetricsBindAddress = net.JoinHostPort("", strconv.Itoa(DefaultOperatorMetricsPort))

	// DefaultOperatorProfilingBindAddress is the default bind address serving the standard Go pprof (/debug/pprof/*) endpoints for the scaling-advisor operator
	DefaultOperatorProfilingBindAddress = net.JoinHostPort("", strconv.Itoa(DefaultOperatorProfilingPort))

	// DefaultAdvisorServiceBindAddress is the default bind address for the standard scaling-advisor service.
	// This service maybe used standalone or embedded within the scaling-advisor operator.
	DefaultAdvisorServiceBindAddress = net.JoinHostPort("", strconv.Itoa(DefaultAdvisorServicePort))

	// DefaultMinKAPIBindAddress is the default bind address for the MinKAPI server.
	// This server maybe used standalone or embedded within the scaling-advisor operator.
	DefaultMinKAPIBindAddress = net.JoinHostPort("", strconv.Itoa(DefaultMinKAPIPort))
)
