//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstancePrice) DeepCopyInto(out *InstancePrice) {
	*out = *in
	if in.UnitCPUPrice != nil {
		in, out := &in.UnitCPUPrice, &out.UnitCPUPrice
		*out = new(float64)
		**out = **in
	}
	if in.UnitMemoryPrice != nil {
		in, out := &in.UnitMemoryPrice, &out.UnitMemoryPrice
		*out = new(float64)
		**out = **in
	}
	out.InstancePriceKey = in.InstancePriceKey
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstancePrice.
func (in *InstancePrice) DeepCopy() *InstancePrice {
	if in == nil {
		return nil
	}
	out := new(InstancePrice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstancePriceKey) DeepCopyInto(out *InstancePriceKey) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstancePriceKey.
func (in *InstancePriceKey) DeepCopy() *InstancePriceKey {
	if in == nil {
		return nil
	}
	out := new(InstancePriceKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstancePriceSet) DeepCopyInto(out *InstancePriceSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstancePriceSet.
func (in *InstancePriceSet) DeepCopy() *InstancePriceSet {
	if in == nil {
		return nil
	}
	out := new(InstancePriceSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstancePriceSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstancePriceSetList) DeepCopyInto(out *InstancePriceSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstancePriceSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstancePriceSetList.
func (in *InstancePriceSetList) DeepCopy() *InstancePriceSetList {
	if in == nil {
		return nil
	}
	out := new(InstancePriceSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstancePriceSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstancePriceSetSpec) DeepCopyInto(out *InstancePriceSetSpec) {
	*out = *in
	if in.Prices != nil {
		in, out := &in.Prices, &out.Prices
		*out = make([]InstancePrice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstancePriceSetSpec.
func (in *InstancePriceSetSpec) DeepCopy() *InstancePriceSetSpec {
	if in == nil {
		return nil
	}
	out := new(InstancePriceSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePlacement) DeepCopyInto(out *NodePlacement) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePlacement.
func (in *NodePlacement) DeepCopy() *NodePlacement {
	if in == nil {
		return nil
	}
	out := new(NodePlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePool) DeepCopyInto(out *NodePool) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]v1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AvailabilityZones != nil {
		in, out := &in.AvailabilityZones, &out.AvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeTemplateRefs != nil {
		in, out := &in.NodeTemplateRefs, &out.NodeTemplateRefs
		*out = make([]NodeTemplateRef, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePool.
func (in *NodePool) DeepCopy() *NodePool {
	if in == nil {
		return nil
	}
	out := new(NodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTemplate) DeepCopyInto(out *NodeTemplate) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Reserved != nil {
		in, out := &in.Reserved, &out.Reserved
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTemplate.
func (in *NodeTemplate) DeepCopy() *NodeTemplate {
	if in == nil {
		return nil
	}
	out := new(NodeTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTemplateRef) DeepCopyInto(out *NodeTemplateRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTemplateRef.
func (in *NodeTemplateRef) DeepCopy() *NodeTemplateRef {
	if in == nil {
		return nil
	}
	out := new(NodeTemplateRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTemplateSet) DeepCopyInto(out *NodeTemplateSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTemplateSet.
func (in *NodeTemplateSet) DeepCopy() *NodeTemplateSet {
	if in == nil {
		return nil
	}
	out := new(NodeTemplateSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeTemplateSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTemplateSetList) DeepCopyInto(out *NodeTemplateSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeTemplateSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTemplateSetList.
func (in *NodeTemplateSetList) DeepCopy() *NodeTemplateSetList {
	if in == nil {
		return nil
	}
	out := new(NodeTemplateSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeTemplateSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTemplateSetSpec) DeepCopyInto(out *NodeTemplateSetSpec) {
	*out = *in
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]NodeTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTemplateSetSpec.
func (in *NodeTemplateSetSpec) DeepCopy() *NodeTemplateSetSpec {
	if in == nil {
		return nil
	}
	out := new(NodeTemplateSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleInFeedback) DeepCopyInto(out *ScaleInFeedback) {
	*out = *in
	if in.AcceptedNodeNames != nil {
		in, out := &in.AcceptedNodeNames, &out.AcceptedNodeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleInFeedback.
func (in *ScaleInFeedback) DeepCopy() *ScaleInFeedback {
	if in == nil {
		return nil
	}
	out := new(ScaleInFeedback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleInItem) DeepCopyInto(out *ScaleInItem) {
	*out = *in
	out.NodePlacement = in.NodePlacement
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleInItem.
func (in *ScaleInItem) DeepCopy() *ScaleInItem {
	if in == nil {
		return nil
	}
	out := new(ScaleInItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleInPlan) DeepCopyInto(out *ScaleInPlan) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScaleInItem, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleInPlan.
func (in *ScaleInPlan) DeepCopy() *ScaleInPlan {
	if in == nil {
		return nil
	}
	out := new(ScaleInPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleOutFeedback) DeepCopyInto(out *ScaleOutFeedback) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScaleOutItemFeedback, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleOutFeedback.
func (in *ScaleOutFeedback) DeepCopy() *ScaleOutFeedback {
	if in == nil {
		return nil
	}
	out := new(ScaleOutFeedback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleOutItem) DeepCopyInto(out *ScaleOutItem) {
	*out = *in
	out.NodePlacement = in.NodePlacement
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleOutItem.
func (in *ScaleOutItem) DeepCopy() *ScaleOutItem {
	if in == nil {
		return nil
	}
	out := new(ScaleOutItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleOutItemFeedback) DeepCopyInto(out *ScaleOutItemFeedback) {
	*out = *in
	in.CreationDeadline.DeepCopyInto(&out.CreationDeadline)
	if in.BackoffUntil != nil {
		in, out := &in.BackoffUntil, &out.BackoffUntil
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleOutItemFeedback.
func (in *ScaleOutItemFeedback) DeepCopy() *ScaleOutItemFeedback {
	if in == nil {
		return nil
	}
	out := new(ScaleOutItemFeedback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleOutPlan) DeepCopyInto(out *ScaleOutPlan) {
	*out = *in
	if in.UnsatisfiedPodNames != nil {
		in, out := &in.UnsatisfiedPodNames, &out.UnsatisfiedPodNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScaleOutItem, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleOutPlan.
func (in *ScaleOutPlan) DeepCopy() *ScaleOutPlan {
	if in == nil {
		return nil
	}
	out := new(ScaleOutPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingAdvice) DeepCopyInto(out *ScalingAdvice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingAdvice.
func (in *ScalingAdvice) DeepCopy() *ScalingAdvice {
	if in == nil {
		return nil
	}
	out := new(ScalingAdvice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingAdvice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingAdviceDiagnostic) DeepCopyInto(out *ScalingAdviceDiagnostic) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingAdviceDiagnostic.
func (in *ScalingAdviceDiagnostic) DeepCopy() *ScalingAdviceDiagnostic {
	if in == nil {
		return nil
	}
	out := new(ScalingAdviceDiagnostic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingAdviceList) DeepCopyInto(out *ScalingAdviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalingAdvice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingAdviceList.
func (in *ScalingAdviceList) DeepCopy() *ScalingAdviceList {
	if in == nil {
		return nil
	}
	out := new(ScalingAdviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingAdviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingAdviceSpec) DeepCopyInto(out *ScalingAdviceSpec) {
	*out = *in
	if in.ScaleOut != nil {
		in, out := &in.ScaleOut, &out.ScaleOut
		*out = new(ScaleOutPlan)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleIn != nil {
		in, out := &in.ScaleIn, &out.ScaleIn
		*out = new(ScaleInPlan)
		(*in).DeepCopyInto(*out)
	}
	if in.Diagnostic != nil {
		in, out := &in.Diagnostic, &out.Diagnostic
		*out = new(ScalingAdviceDiagnostic)
		**out = **in
	}
	out.ConstraintRef = in.ConstraintRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingAdviceSpec.
func (in *ScalingAdviceSpec) DeepCopy() *ScalingAdviceSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingAdviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingAdviceStatus) DeepCopyInto(out *ScalingAdviceStatus) {
	*out = *in
	if in.Feedback != nil {
		in, out := &in.Feedback, &out.Feedback
		*out = new(ScalingFeedback)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingAdviceStatus.
func (in *ScalingAdviceStatus) DeepCopy() *ScalingAdviceStatus {
	if in == nil {
		return nil
	}
	out := new(ScalingAdviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingConstraint) DeepCopyInto(out *ScalingConstraint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingConstraint.
func (in *ScalingConstraint) DeepCopy() *ScalingConstraint {
	if in == nil {
		return nil
	}
	out := new(ScalingConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingConstraint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingConstraintList) DeepCopyInto(out *ScalingConstraintList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalingConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingConstraintList.
func (in *ScalingConstraintList) DeepCopy() *ScalingConstraintList {
	if in == nil {
		return nil
	}
	out := new(ScalingConstraintList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingConstraintList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingConstraintSpec) DeepCopyInto(out *ScalingConstraintSpec) {
	*out = *in
	if in.NodePools != nil {
		in, out := &in.NodePools, &out.NodePools
		*out = make([]NodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingConstraintSpec.
func (in *ScalingConstraintSpec) DeepCopy() *ScalingConstraintSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingConstraintSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingConstraintStatus) DeepCopyInto(out *ScalingConstraintStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingConstraintStatus.
func (in *ScalingConstraintStatus) DeepCopy() *ScalingConstraintStatus {
	if in == nil {
		return nil
	}
	out := new(ScalingConstraintStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingFeedback) DeepCopyInto(out *ScalingFeedback) {
	*out = *in
	if in.ScaleOut != nil {
		in, out := &in.ScaleOut, &out.ScaleOut
		*out = new(ScaleOutFeedback)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleIn != nil {
		in, out := &in.ScaleIn, &out.ScaleIn
		*out = new(ScaleInFeedback)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingFeedback.
func (in *ScalingFeedback) DeepCopy() *ScalingFeedback {
	if in == nil {
		return nil
	}
	out := new(ScalingFeedback)
	in.DeepCopyInto(out)
	return out
}
