apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  qps: {{.QPS}}
  burst: {{.Burst}}
  contentType: application/json
  kubeconfig: {{.KubeConfigPath}}
enableProfiling: true
leaderElection:
  leaderElect: false
profiles:
  - schedulerName: default-scheduler
  - schedulerName: bin-packing-scheduler
    pluginConfig:
      - name: NodeResourcesFit
        args:
          scoringStrategy:
            type: MostAllocated
    plugins:
      score:
        disabled:
          - name: NodeResourcesBalancedAllocation
