apiVersion: v1
kind: Config
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: {{.URL}}
    name: minkapi
contexts:
  - context:
      cluster: minkapi
      user: minkapi-user
      namespace: default
    name: minkapi-context
current-context: minkapi-context
users:
  - name: minkapi-user
    user: {}
