# Force neutral theme and override the text color token (N1 -> black)
vars: {
  d2-config: {
    theme-id: 103
    theme-overrides: {
       N2: "#000000"
    }
  }
}
api: {
  label: API
  shape: package
  icon: https://icons.terrastruct.com/azure%2FWeb%20Service%20Color%2FAPI%20Connections.svg
}

common: {
  label: Common Module
  shape: package
  icon: "box.svg"
}


minkapi: {
  label: MinKAPI Module
  shape: package
  icon: "log-in.svg"
  icon: "kube.svg"
}

service: {
  label: Service Module
  shape: package
  icon: "map.svg"
}

operator: {
  label: Operator Module
  shape: package
  icon: "repeat.svg"
}

tools: {
  label: Tools Module
  shape: package
  icon: https://icons.terrastruct.com/aws%2F_General%2FToolkit_light-bg.svg
}

generator: {
  label: "Generator Pkg"
  shape: page
  icon: "engine-belt.svg"
}

simulation: {
  label: "Simulation Pkg"
  shape: page
  icon: "sandbox.svg"
}

