name: Build

on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
        default: snapshot
        description: |
          the mode to use. either `snapshot` or `release`. Will affect effective version, as well
          as target-oci-registry.

jobs:
  prepare:
    uses: gardener/cc-utils/.github/workflows/prepare.yaml@master
    with:
      mode: ${{ inputs.mode }}
    permissions:
      contents: read

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@master
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: run-build
        run: make tidy && make build

  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        args:
          - run: make test-unit
          # add make targets for integration-test and e2e tests once these are available
    steps:
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@master
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: run-unit-tests
        shell: bash
        run: |
          set -euo pipefail
          ${{ matrix.args.run }}

  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@master
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: run-check
        run: make check

  sast-lint:
    uses: gardener/cc-utils/.github/workflows/sastlint-ocm.yaml@master
    permissions:
      contents: read
    with:
      linter: gosec
      run: make sast-report
      go-version: '1.25'



